"""
MoveGUI

#A GUI to do multiple moves test. Minor change from movegui.py. Used for DESI fiber entanglement test at first.
# This GUI can move a single/all positioners by sending can command (quick) or talking to the conf file for each positioner first (slow).
# The differece is: if the wiring is flipped, sending can command will have the rotation direction flipped, but the non-can method will fix it.
# Use the 'CAN' checkbox to enable can command mode.
# Select 'ALL' or a specific positioner before making movement.
# Show INFO  will show the positioner Silicon ID, Full Sillicon ID, and firmware version
# Center will center the positioner so that the installation of fibers will be easier.
# First set the round of test you want to run, and click 'start test'.
# Refresh/Restart will restart the GUI. After plugging/unplugging positioners, you should click this botton.
# Update petalcontroller.py on beaglebone before using this code.
# On different computers, you probably need to set the path differently. Search all the os.path in this code and modify them.
# Tell the code where to find google_access_account.json when setting up for another computer.
# Needs gspread and oauth2client packages. googlesheets.py under data_processing_scripts folder is made by Brandon, and the google_access_account.json is generated by him too.
# History: V1.0   Kai Zhang @LBNL  2018-3-9   Contact: zkdtckk@gmail.com


"""
import os
import sys
import datetime
sys.path.append(os.path.abspath('../petal/'))
sys.path.append(os.path.abspath('../posfidfvc/'))
sys.path.append(os.path.abspath('/home/msdos/focalplane/positioner_logs/'))
import fvchandler
import petal
import petalcomm
import posmovemeasure
import posconstants as pc
import summarizer
import numpy as np
import time
import pos_xytest_plot
import um_test_report as test_report
import traceback
import configobj
import tkinter
import tkinter.filedialog
import tkinter.messagebox
import tkinter.simpledialog
import csv
import collections
from tkinter import *
import googlesheets
import time


class Fiber_Test_GUI(object):
    def __init__(self,hwsetup_conf='',xytest_conf=''):
        global gui_root
        gui_root = tkinter.Tk()

        w=200
        h=100
        ws=gui_root.winfo_screenwidth()
        hs=gui_root.winfo_screenheight()
        x=(ws/2)-(w/2)
        y=(hs/2)-(h/2)
        gui_root.geometry('%dx%d+%d+%d' % (w,h,x,y))

        self.e1=Entry(gui_root,width=5)
        self.e1.grid(row=0,column=1)
        Label(gui_root,text="Petal ID:").grid(row=0)

        Button(gui_root,text='OK',width=10,command=self.set_ptl_id).grid(row=0,column=2,sticky=W,pady=4)

        mainloop()

        gui_root = tkinter.Tk()

        self.simulate = False
        self.logfile='Fiber_Test_GUI.log'
        fvc_type='simulator'
        fidids=['F021']
        gui_root.title='Move Controll for Petal '+str(self.ptl_id)
        self.pcomm=petalcomm.PetalComm(self.ptl_id)
        self.mode = 0
        #petalcomm.
   #     info=self.petalcomm.get_device_status()
        canbus='can0'
        self.bus_id=canbus
        self.info = self.pcomm.get_posfid_info(canbus)
        self.posids = []
        print(self.info)
        for key in sorted(self.info.keys()):
            if len(str(key))==2:
                self.posids.append('M000'+str(key))
            elif len(str(key))==3:
                self.posids.append('M00'+str(key))
            elif len(str(key))==4:
                self.posids.append('M0'+str(key))
            elif len(str(key))==5:
                self.posids.append('M'+str(key))
        self.ptl = petal.Petal(self.ptl_id, self.posids, fidids, simulator_on=self.simulate, printfunc=self.logwrite)
        self.fvc = fvchandler.FVCHandler(fvc_type,printfunc=self.logwrite,save_sbig_fits=False)
        self.m = posmovemeasure.PosMoveMeasure([self.ptl],self.fvc,printfunc=self.logwrite)

# GUI input
        w=1600
        h=700
        ws=gui_root.winfo_screenwidth()
        hs=gui_root.winfo_screenheight()
        x=(ws/2)-(w/2)
        y=(hs/2)-(h/2)
        gui_root.geometry('%dx%d+%d+%d' % (w,h,x,y))

        Button(gui_root,text='Set',width=10,command=self.set_num_sim).grid(row=0,column=4,sticky=W,pady=4)

        Label(gui_root,text="Rotation Angel").grid(row=0,column=0)
        self.e1=Entry(gui_root)
        self.e1.grid(row=0,column=1)
        self.e1.insert(0,'190')

        Label(gui_root,text="Set Sim Number").grid(row=0,column=2)
        self.e2=Entry(gui_root)
        self.e2.grid(row=0,column=3)

        Button(gui_root,text='Theta CW',width=10,command=self.theta_cw_degree).grid(row=3,column=1,sticky=W,pady=4)
        Button(gui_root,text='Theta CCW',width=10,command=self.theta_ccw_degree).grid(row=4,column=1,sticky=W,pady=4)
        self.mode=IntVar(gui_root)
        self.mode.set(1)
        Checkbutton(gui_root, text='CAN', variable=self.mode).grid(row=3,column=2,sticky=W,pady=4)
        Button(gui_root,text='Phi CW',width=10,command=self.phi_cw_degree).grid(row=3,column=0,sticky=W,pady=4)
        Button(gui_root,text='Phi CCW',width=10,command=self.phi_ccw_degree).grid(row=4,column=0,sticky=W,pady=4)
        Button(gui_root,text='Show INFO',width=10,command=self.show_info).grid(row=5,column=1,sticky=W,pady=4)
        Button(gui_root,text='Start Test',width=10,command=self.start_test).grid(row=5,column=3,sticky=W,pady=4)
        Button(gui_root,text='Center',width=10,command=self.center).grid(row=4,column=2,sticky=W,pady=4)
        self.listbox1 = Listbox(gui_root, width=20, height=20)
        self.listbox1.grid(row=6, column=0,rowspan=10,pady=4,padx=15)
        # create a vertical scrollbar to the right of the listbox
        yscroll_listbox1 = Scrollbar(command=self.listbox1.yview, orient=tkinter.VERTICAL)
        yscroll_listbox1.grid(row=6, column=0, rowspan=10,sticky=tkinter.E+tkinter.N+tkinter.S,pady=5)
        self.listbox1.configure(yscrollcommand=yscroll_listbox1.set)
        self.listbox1.insert(tkinter.END,'ALL')
        for key in sorted(self.info.keys()):
            if len(str(key))==2:
                self.listbox1.insert(tkinter.END,'M000'+str(key))
            elif len(str(key))==3:
                self.listbox1.insert(tkinter.END,'M00'+str(key))
            elif len(str(key))==4:
                self.listbox1.insert(tkinter.END,'M0'+str(key))
            elif len(str(key))==5:
                self.listbox1.insert(tkinter.END,'M'+str(key))

        self.listbox1.bind('<ButtonRelease-1>', self.get_list)


        yscroll_text1 = Scrollbar(gui_root, orient=tkinter.VERTICAL)
        yscroll_text1.grid(row=6, column=4, rowspan=20,sticky=tkinter.E+tkinter.N+tkinter.S,pady=5)
        self.text1=Text(gui_root,height=30,width=90,wrap=WORD)
        self.text1.grid(row=6,column=1,columnspan=4,rowspan=20,sticky=W,pady=4,padx=15)
        self.text1.configure(yscrollcommand=yscroll_text1.set)
        yscroll_text1.config(command=self.text1.yview)
# Right part of the GUI to write to Acceptance Traveller

#       Load the information
        Label(gui_root,text="You selected").grid(row=3,column=5)
        self.e_selected=Entry(gui_root)
        self.e_selected.grid(row=3,column=6)


        yscroll_text2 = Scrollbar(gui_root, orient=tkinter.VERTICAL)
        yscroll_text2.grid(row=6, column=6, rowspan=20,sticky=tkinter.E+tkinter.N+tkinter.S,pady=5)
        self.text2=Text(gui_root,height=30,width=38)
        self.text2.grid(row=6,column=5,columnspan=2,rowspan=20,sticky=W+E+N+S,pady=4,padx=15)
        self.text2.tag_configure('bold_italics', font=('Arial', 12, 'bold', 'italic'))
        self.text2.tag_configure('big', font=('Verdana', 12, 'bold','bold'))
        self.text2.tag_configure('green', foreground='#476042', font=('Tempus Sans ITC', 12, 'bold'))
        self.text2.tag_configure('red', foreground='#ff0000', font=('Tempus Sans ITC', 12, 'bold'))
        self.text2.tag_configure('yellow', background='#ffff00', font=('Tempus Sans ITC', 12, 'bold'))
        self.text2.configure(yscrollcommand=yscroll_text2.set)
        yscroll_text2.config(command=self.text2.yview)


##      checkboxes

        self.plug=IntVar(gui_root)
        self.entered=IntVar(gui_root)
        self.theta_work=IntVar(gui_root)
        self.phi_work=IntVar(gui_root)
        self.plug.set(1)
        self.entered.set(1)
        self.theta_work.set(1)
        self.phi_work.set(1)

        column_entry=7
        Checkbutton(gui_root, text='Plug?', variable=self.plug).grid(row=4,column=column_entry,sticky=W,pady=4)
        Checkbutton(gui_root, text='POS INFO Entered?', variable=self.entered).grid(row=5,column=column_entry,sticky=W,pady=4)
        Checkbutton(gui_root, text='Theta Work?', variable=self.theta_work).grid(row=6,column=column_entry,sticky=W,pady=4)
        Checkbutton(gui_root, text='Phi Work?', variable=self.phi_work).grid(row=7,column=column_entry,sticky=W,pady=4)

        Label(gui_root,text="Note").grid(row=8,column=column_entry)
        self.e3=Entry(gui_root)
        self.e3.grid(row=8,column=column_entry+1)
        Label(gui_root,text="Send PFA Date").grid(row=9,column=column_entry)
        self.e4=Entry(gui_root)
        self.e4.insert(END,'{:%Y-%m-%d %H:%M:%S}'.format(datetime.datetime.now()))
        self.e4.grid(row=9,column=column_entry+1)
        Label(gui_root,text="Send PFA Name").grid(row=10,column=column_entry)
        self.e5=Entry(gui_root)
        self.e5.grid(row=10,column=column_entry+1)
        Label(gui_root,text="Tote").grid(row=11,column=column_entry)
        self.box_options = [    "GREY TOTE\n---------\nREADY FOR PFA INSTALL",    "GREY TOTE\n---------\nINCOMING INSPECTION IN PROGRESS",    "LARGE TOTE\n--------\nFAIL REVIEW LATER", "LARGE TOTE\n--------\nFAIL PERMANENT"]
        self.box_goto = StringVar(gui_root)
        self.box_goto.set("Where will you put me?") # default value
        self.drop1 = OptionMenu(gui_root, self.box_goto, *self.box_options)
        self.drop1.grid(row=11,column=column_entry+1)

        #Label(gui_root,text="Update DB?, your init").grid(row=12,column=column_entry)
        #self.e6=Entry(gui_root)
        #self.e6.grid(row=12,column=column_entry+1)



#        Button(gui_root,text='Plot List',width=10,command=click_plot_list).grid(row=4,column=2,sticky=W,pady=4)
        Button(gui_root,text='Refresh/Restart',width=15,command=self.restart).grid(row=0,column=8,sticky=W,pady=4)
        Button(gui_root,text='Clear',width=15,command=self.clear1).grid(row=5,column=4,sticky=W,pady=4)
        Button(gui_root,text='Clear',width=15,command=self.clear2).grid(row=5,column=6,sticky=W,pady=4)

        photo = PhotoImage(file='desi_logo.gif')
        photo=photo.subsample(7)
        label = Label(image=photo,width=20,height=100)
        label.image = photo # keep a reference!
        label.grid(row=16, column=0, columnspan=1, rowspan=20,sticky=W+E+N+S, padx=5, pady=5)


        mainloop()

    def set_ptl_id(self):
        self.ptl_id=self.e1.get()
        gui_root.destroy()
    def set_num_sim(self):
            self.num_sim=int(self.e2.get())
            self.text1.insert(END,'Set to '+str(self.e2.get())+' round of moves. \n')

    def get_list(self,event):
        # get selected line index
        index = self.listbox1.curselection()[0]
        # get the line's text
        self.selected=self.listbox1.get(index)
        if self.selected == 'ALL':
            self.selected_posid=self.posids
            self.selected_can=20000
        else:
            self.selected_posid=self.selected
            self.selected_can=int(str(self.selected[1:6]))
        self.e_selected.delete(0,END)
        self.e_selected.insert(0,str(self.selected_can))

    def format_sids(self, sid_dict):
        for key,value in sid_dict.items():
            sid_dict[key] = ":".join("{:02x}".format(c) for c in value)
        return sid_dict

    def show_info(self):
        for key in sorted(self.info.keys()):
            self.text1.insert(END,str(key)+' '+str(self.info[key])+'\n')


    def theta_cw_degree(self):
        degree=float(self.e1.get())
        dtdp=[-degree,0]

        if self.mode.get()==1:
            self.pcomm.move('can0', self.selected_can, 'cw', 'cruise', 'theta', degree)
        else:
            self.ptl.quick_direct_dtdp(self.selected_posid,dtdp)

    def theta_ccw_degree(self):
        degree=float(self.e1.get())
        dtdp=[degree,0]
        if self.mode.get()==1:
            self.pcomm.move('can0', self.selected_can, 'ccw', 'cruise', 'theta', degree)
        else:
            self.ptl.quick_direct_dtdp(self.selected_posid,dtdp)

    def phi_cw_degree(self):
        degree=float(self.e1.get())
        dtdp=[0,-degree]
        if self.mode.get()==1:
            self.pcomm.move('can0', self.selected_can, 'cw', 'cruise', 'phi', degree)
        else:
            self.ptl.quick_direct_dtdp(self.selected_posid,dtdp)

    def phi_ccw_degree(self):
        degree=float(self.e1.get())
        dtdp=[0,degree]
        if self.mode.get()==1:
            self.pcomm.move('can0', self.selected_can, 'ccw', 'cruise', 'phi', degree)
        else:
            self.ptl.quick_direct_dtdp(self.selected_posid,dtdp)

    def center(self):
        if self.mode.get()==1:
            self.pcomm.move('can0', 20000, 'cw', 'cruise', 'theta', 400)
            time.sleep(4)
            self.pcomm.move('can0', 20000, 'ccw', 'cruise', 'phi', 200)
            time.sleep(2)
            self.pcomm.move('can0', 20000, 'ccw', 'cruise', 'theta', 195)


       #     self.pcomm.move('can0', 20000, 'ccw', 'cruise', 'phi', 200)
        else:
            dtdp=[-400,200]
            self.ptl.quick_direct_dtdp(self.posids,dtdp)
            dtdp=[195,0]
            self.ptl.quick_direct_dtdp(self.posids,dtdp)
            self.text1.insert(END,'Centering Done \n')
    def start_test(self):
        if self.mode.get()==1:
            for i in range(self.num_sim):
                print(i,'th move in '+str(self.num_sim))
                for posid in self.posids:
                    print('\n',posid)
                    self.ptl.schedule.request_target(posid, 'posTP',  random.uniform(0, 360), random.uniform(0,190), log_note='')
                self.ptl.schedule._schedule_without_anticollision() # Make move_tables
                self.ptl.send_move_tables()

        else:
            for i in range(self.num_sim):
                print(i,'th move in '+str(self.num_sim))
                self.text2.insert('0.0',str(i)+'th move in '+str(self.num_sim)+' \n')
                self.pcomm.move('can0', 20000, 'cw', 'cruise', 'phi', 200)
                time.sleep(2)
                self.pcomm.move('can0', 20000, 'cw', 'cruise', 'theta', 400)
                time.sleep(4)
                self.pcomm.move('can0', 20000, 'ccw', 'cruise', 'theta', 400)
                time.sleep(4)
                self.pcomm.move('can0', 20000, 'ccw', 'cruise', 'phi', 200)
                time.sleep(2)

    def write_siid(self):
        self.text1.insert(END,'Writing SiID \n')
        for key in sorted(self.info.keys()):
            info_this=self.info[key]
            pos_this=googlesheets.read(self.sheet1,20+int(key),1,False,False)
            if (float(key)<7000 and float(pos_this)== float(key)):
                googlesheets.write(self.sheet1,int(key)+20,5,str(key),False,False) # POSID
                googlesheets.write(self.sheet1,int(key)+20,6,info_this[3],False,False) # SI_ID
                googlesheets.write(self.sheet1,int(key)+20,7,info_this[2],False,False) # Full SI_ID
                googlesheets.write(self.sheet1,int(key)+20,15,info_this[0],False,False) # Firmware_ver
                test=googlesheets.read(self.sheet1,int(key)+20,6,False,False)
                if test == info_this[3]:
                    self.text1.insert(END,'Writing '+str(key)+' successfully \n')
                else:
                    self.text1.insert(END,'Writing '+str(key)+' failed. \n Check doc '+url+'\n')
            elif float(key)>7000:
                self.text1.insert(END,'Is '+str(key)+' a fiducial? Not writing. \n')
            else:
                self.text1.insert(END,'Posid and RowID are not consistent. Check the integrity of the file. \nGo to '+url+' \n' )
        self.text1.insert(END,'Writing Sheets Done \n')

    def load_acceptance_traveller(self):
        self.text2.delete('0.0', END)
        self.e4.delete(0, END)
        self.e4.insert(END,'{:%Y-%m-%d %H:%M:%S}'.format(datetime.datetime.now()))
        if self.selected_can == 20000:
            self.text2.insert('0.0','Cannot load all positioners simultaneously. \nSelect one positioner.\n')
        else:
            # Find the column we want first
            pos_list=googlesheets.read_row(self.sheet2,2,False)
            column_skip=6 # Skip the first 6 description columns
            pos_list=np.array(pos_list[column_skip:])
            selected_can_str=str(self.selected_can)
            selected_can_str.strip()
            ind=np.where(pos_list == selected_can_str)
            if not ind[0]:
                self.text2.insert('0.0','Cannot find this positioner while loading... \n')
            else:
                col_id=ind[0][0]+column_skip+1
                column_info=googlesheets.read_col(self.sheet2,col_id,False)
                column_info_title=googlesheets.read_col(self.sheet2,2,False)
                ref_list=['', '', '', '', '', '', '', '',  'A','','', '', '', '', '','','Y', 'Y', 'Y', 'B', 'B', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'A', 'P', '', '', '', '', 'Y', 'Y', 'Y', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '','','','','','']
                #['', '', '', '2017-10-23', '', '1748', '5899', '', '', 'John Mourelatos', '2017-10-23', '', '1.15', 'A', '4.3', 'A', '', '', '', 'John Mourelatos', '2017-10-23', 'Y', 'Y', 'Y', 'B', 'B', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'A', '', '', 'John Mourelatos', '2017-10-23', 'P', '0.00997', '0.12588', 'SKIP', 'SKIP', '', '', 'Y', 'Y', 'Y', 'Y', '', '', '', '', '0.13585', '', 'YES', '', '', '', '2017-11-03', 'KAI ZHANG', 'GREY TOTE\n---------\nREADY FOR PFA INSTALL', 'KZ']

                for i in range(len(column_info)):
                    if ref_list[i] == '' or column_info[i] == ref_list[i]:
                        if column_info_title[i] == 'DOCUMENT_DEVIATION' and column_info[i] != '':
                            self.text2.insert(END,str(column_info_title[i])+': ','big')
                            self.text2.insert(END,str(column_info[i])+'\n','yellow')
                        elif column_info_title[i] == 'ENVELOPE_GAGE' and column_info[i] in ['C','D']:
                            self.text2.insert(END,str(column_info_title[i])+': ','big')
                            self.text2.insert(END,str(column_info[i])+'\n','red')
                        elif column_info_title[i] == 'ENVELOPE_GAGE' and column_info[i] == '':
                            self.text2.insert(END,str(column_info_title[i])+': ','yellow')
                        elif column_info_title[i] == 'THETA_PHI_ANGLE' and float(column_info[i])>0.5:
                            self.text2.insert(END,str(column_info_title[i])+': ','big')
                            self.text2.insert(END,str(column_info[i])+'\n','red')
                        elif column_info_title[i] == 'FERRULE_PHI_ANGLE' and float(column_info[i])>0.5:
                            self.text2.insert(END,str(column_info_title[i])+': ','big')
                            self.text2.insert(END,str(column_info[i])+'\n','red')
                        elif column_info_title[i] == 'COMBINED_ANGLE':
                            if column_info[i] == '':
                               self.text2.insert(END,str(column_info_title[i])+': \n','yellow')
                            elif float(column_info[i])>0.5:
                                self.text2.insert(END,str(column_info_title[i])+': ','big')
                                self.text2.insert(END,str(column_info[i])+'\n','red')
                            else:
                                self.text2.insert(END,str(column_info_title[i])+': ','big')
                                self.text2.insert(END,str(column_info[i])+'\n','green')
                        else:
                            self.text2.insert(END,str(column_info_title[i])+': ','big')
                            self.text2.insert(END,str(column_info[i])+'\n','green')
                    else:
                        self.text2.insert(END,str(column_info_title[i])+': ','big')
                        self.text2.insert(END,str(column_info[i])+'\n','red')



    def write_acceptance_traveller(self):
        self.text2.delete('0.0', END)
        self.e4.delete(0, END)
        self.e4.insert(END,'{:%Y-%m-%d %H:%M:%S}'.format(datetime.datetime.now()))
        if self.selected_can == 20000:
            self.text2.insert('0.0','Cannot write all positioners simultaneously for safety reason. \nSelect one positioner.\n')
        else:
            # Find the column we want first
            pos_list=googlesheets.read_row(self.sheet2,2,False)
            column_skip=6 # Skip the first 6 description columns
            pos_list=np.array(pos_list[column_skip:])
            selected_can_str=str(self.selected_can)
            selected_can_str.strip()
            ind=np.where(pos_list == selected_can_str)
            if not ind[0]:
                self.text2.insert('0.0','Cannot find this positioner...\n')
            else:
                col_id=ind[0][0]+column_skip+1
                if self.plug.get()==1:
                    googlesheets.write(self.sheet2,38,col_id,'Y',False,False)
                else:
                    googlesheets.write(self.sheet2,38,col_id,'N',False,False)
                if self.entered.get()==1:
                    googlesheets.write(self.sheet2,39,col_id,'Y',False,False)
                else:
                    googlesheets.write(self.sheet2,39,col_id,'N',False,False)
                if self.theta_work.get()==1:
                    googlesheets.write(self.sheet2,40,col_id,'Y',False,False)
                else:
                    googlesheets.write(self.sheet2,40,col_id,'N',False,False)
                if self.phi_work.get()==1:
                    googlesheets.write(self.sheet2,41,col_id,'Y',False,False)
                else:
                    googlesheets.write(self.sheet2,41,col_id,'N',False,False)
                googlesheets.write(self.sheet2,42,col_id,self.e3.get(),False,False)  #53 before
                if self.box_goto.get() == self.box_options[0]:   # If accept for PFA installation
                    googlesheets.write(self.sheet2,58,col_id,self.e4.get(),False,False)
                    googlesheets.write(self.sheet2,59,col_id,self.e5.get(),False,False)
                    googlesheets.write(self.sheet2,60,col_id,self.box_goto.get(),False,False)
                    googlesheets.write(self.sheet2,61,'Y',False,False)
                else:
                    googlesheets.write(self.sheet2,58,col_id,'No',False,False)
                    googlesheets.write(self.sheet2,59,col_id,'No',False,False)
                    googlesheets.write(self.sheet2,60,col_id,self.box_goto.get(),False,False)
                    googlesheets.write(self.sheet2,61,'Y',False,False)
                self.load_acceptance_traveller()


    def restart(self):
        gui_root.destroy()
        Fiber_Test_GUI()
    def clear1(self):
        self.text1.delete('0.0', END)
    def clear2(self):
        self.text2.delete('0.0', END)

    def logwrite(self,text,stdout=True):
        """Standard logging function for writing to the test traveler log file.
        """
        line = '# ' + pc.timestamp_str() + ': ' + text
        with open(self.logfile,'a') as fh:
            fh.write(line + '\n')
        if stdout:
            print(line)

if __name__=="__main__":
    gui = Fiber_Test_GUI()
